/**
 * Site configuration — update basePath when deploying to GitHub Pages.
 * Generated by prepare-deploy.js
 */
window.SITE_CONFIG = {
  basePath: '/stack-ready',
  buildId: '4d200360a8b3'
};

/** Purge stale service-worker + HTTP caches when a new deploy ships (once per build). */
(function () {
  var id = window.SITE_CONFIG && window.SITE_CONFIG.buildId;
  if (!id) return;
  var key = 'sr_build_id';
  var prev = null;
  try { prev = localStorage.getItem(key); } catch (e) { return; }
  if (!prev) {
    try { localStorage.setItem(key, id); } catch (e) { /* ignore */ }
    return;
  }
  if (prev === id) return;

  // Save new build id FIRST — prevents infinite reload loop
  try { localStorage.setItem(key, id); } catch (e) { return; }

  var onceKey = 'sr_purged_' + id;
  try {
    if (sessionStorage.getItem(onceKey)) return;
    sessionStorage.setItem(onceKey, '1');
  } catch (e) { /* ignore */ }

  var purge = function () {
    if ('caches' in window) {
      return caches.keys().then(function (keys) {
        return Promise.all(keys.map(function (k) { return caches.delete(k); }));
      });
    }
  };
  var done = function () {
    try { location.reload(); } catch (e) { /* ignore */ }
  };
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations()
      .then(function (regs) { return Promise.all(regs.map(function (r) { return r.unregister(); })); })
      .then(purge)
      .then(done);
  } else {
    purge().then(done);
  }
})();
