/**
 * Site configuration — update basePath when deploying to GitHub Pages.
 * Generated by prepare-deploy.js
 */
window.SITE_CONFIG = {
  basePath: '/stack-ready',
  buildId: '554013cc7f15'
};

/** Purge stale service-worker + HTTP caches when a new deploy ships. */
(function () {
  var id = window.SITE_CONFIG && window.SITE_CONFIG.buildId;
  if (!id) return;
  var key = 'sr_build_id';
  var prev = null;
  try { prev = localStorage.getItem(key); } catch (e) { return; }
  if (prev && prev !== id) {
    var reload = function () { try { location.reload(); } catch (e) { /* ignore */ } };
    var purge = function () {
      if ('caches' in window) {
        return caches.keys().then(function (keys) {
          return Promise.all(keys.map(function (k) { return caches.delete(k); }));
        });
      }
    };
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistrations()
        .then(function (regs) { return Promise.all(regs.map(function (r) { return r.unregister(); })); })
        .then(purge)
        .then(reload);
    } else {
      purge().then(reload);
    }
    return;
  }
  try { localStorage.setItem(key, id); } catch (e) { /* ignore */ }
})();
