/**
 * Copies all study guides into website/content/ for static hosting (GitHub Pages).
 * Optionally sets basePath in config.js for project-site URLs.
 *
 * Usage:
 *   node prepare-deploy.js
 *   node prepare-deploy.js stack-ready    # sets basePath to /stack-ready
 */

const fs = require('fs');
const path = require('path');

const WEBSITE_DIR = __dirname;
const PREP_DIR = path.dirname(WEBSITE_DIR);
const CONTENT_DIR = path.join(WEBSITE_DIR, 'content');
const CONFIG_FILE = path.join(WEBSITE_DIR, 'config.js');
const repoName = process.argv[2] || '';

const EXTENSIONS = new Set(['.md', '.txt']);

function copyGuides() {
  if (!fs.existsSync(CONTENT_DIR)) fs.mkdirSync(CONTENT_DIR, { recursive: true });

  const files = fs.readdirSync(PREP_DIR).filter(f => EXTENSIONS.has(path.extname(f).toLowerCase()));
  let count = 0;
  for (const file of files) {
    fs.copyFileSync(path.join(PREP_DIR, file), path.join(CONTENT_DIR, file));
    count++;
  }
  console.log(`Copied ${count} guide files to website/content/`);
}

function updateConfig() {
  const basePath = repoName ? `/${repoName.replace(/^\//, '')}` : '';
  const config = `/**
 * Site configuration — update basePath when deploying to GitHub Pages.
 * Generated by prepare-deploy.js
 */
window.SITE_CONFIG = {
  basePath: '${basePath}'
};
`;
  fs.writeFileSync(CONFIG_FILE, config, 'utf8');
  console.log(`config.js basePath = '${basePath}'${basePath ? ' (GitHub Pages project site)' : ' (local / user site)'}`);
}

copyGuides();
updateConfig();
console.log('\nNext: commit, push, enable GitHub Pages on /website folder.');
console.log('See DEPLOY_GITHUB_PAGES.md for full steps.');
