/**
 * Copies all study guides into website/content/ for static hosting (GitHub Pages).
 * Optionally sets basePath in config.js for project-site URLs.
 *
 * Usage:
 *   node prepare-deploy.js
 *   node prepare-deploy.js stack-ready    # sets basePath to /stack-ready
 */

const fs = require('fs');
const path = require('path');

const WEBSITE_DIR = __dirname;
const PREP_DIR = path.dirname(WEBSITE_DIR);
const CONTENT_DIR = path.join(WEBSITE_DIR, 'content');
const CONFIG_FILE = path.join(WEBSITE_DIR, 'config.js');
const META_FILE = path.join(WEBSITE_DIR, 'assets', 'js', 'content-meta.js');
const repoName = process.argv[2] || '';
const WORDS_PER_MIN = 200;

const EXTENSIONS = new Set(['.md', '.txt']);
const EXCLUDE_FILES = new Set(['00_Study_Plan_Day_by_Day.txt']);

function copyGuides() {
  if (!fs.existsSync(CONTENT_DIR)) fs.mkdirSync(CONTENT_DIR, { recursive: true });

  const files = fs.readdirSync(PREP_DIR).filter(f => {
    const ext = path.extname(f).toLowerCase();
    return EXTENSIONS.has(ext) && !EXCLUDE_FILES.has(f);
  });
  let count = 0;
  for (const file of files) {
    fs.copyFileSync(path.join(PREP_DIR, file), path.join(CONTENT_DIR, file));
    count++;
  }
  // Remove excluded files if previously deployed
  for (const excluded of EXCLUDE_FILES) {
    const p = path.join(CONTENT_DIR, excluded);
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }
  console.log(`Copied ${count} guide files to website/content/`);
}

function stripMarkdown(raw) {
  return raw
    .replace(/```[\s\S]*?```/g, ' ')      // code fences
    .replace(/`[^`]*`/g, ' ')             // inline code
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')// images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // links -> text
    .replace(/[#>*_~|-]/g, ' ');          // md punctuation
}

function generateContentMeta() {
  const files = fs.readdirSync(PREP_DIR).filter(f => {
    const ext = path.extname(f).toLowerCase();
    return EXTENSIONS.has(ext) && !EXCLUDE_FILES.has(f);
  });

  const meta = {};
  for (const file of files) {
    const raw = fs.readFileSync(path.join(PREP_DIR, file), 'utf8');
    const words = (stripMarkdown(raw).match(/\S+/g) || []).length;
    meta[file] = { words, minutes: Math.max(1, Math.round(words / WORDS_PER_MIN)) };
  }

  const out = `/**
 * Per-guide reading metadata (word count + estimated minutes).
 * AUTO-GENERATED by prepare-deploy.js — do not edit by hand.
 */
window.CONTENT_META = ${JSON.stringify(meta, null, 2)};
`;
  fs.writeFileSync(META_FILE, out, 'utf8');
  console.log(`Generated reading metadata for ${Object.keys(meta).length} guides.`);
}

function updateConfig() {
  const basePath = repoName ? `/${repoName.replace(/^\//, '')}` : '';
  const config = `/**
 * Site configuration — update basePath when deploying to GitHub Pages.
 * Generated by prepare-deploy.js
 */
window.SITE_CONFIG = {
  basePath: '${basePath}'
};
`;
  fs.writeFileSync(CONFIG_FILE, config, 'utf8');
  console.log(`config.js basePath = '${basePath}'${basePath ? ' (GitHub Pages project site)' : ' (local / user site)'}`);
}

copyGuides();
generateContentMeta();
updateConfig();
console.log('\nNext: commit, push, enable GitHub Pages on /website folder.');
console.log('See DEPLOY_GITHUB_PAGES.md for full steps.');
