/**
 * AUTO-GENERATED by prepare-deploy.js — build reloadfix01
 * Network-first for all same-origin assets; cache is offline fallback only.
 */
const CACHE = 'stackready-reloadfix01';

self.addEventListener('install', () => {
  // Normal install — activate on next visit (avoids reload flicker)
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

function networkFirst(request) {
  return caches.open(CACHE).then((cache) =>
    fetch(request, { cache: 'no-store' })
      .then((res) => {
        if (res && res.ok) cache.put(request, res.clone());
        return res;
      })
      .catch(() => cache.match(request))
  );
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(networkFirst(req));
});
